### PR TITLE
Trigger reload

### PR DESCRIPTION
**Pull request by an-OK-squirrel**

### CODE REVIEW

**Comment by an-OK-squirrel** [comment]
Oh, whoops! I meant to do this on my repo and I hit enter too soon :(

**Comment by donatj** [comment]
What does this actually do? Is this something I'd want to merge back into my repo?

**Comment by an-OK-squirrel** [comment]
No. I was trying to figure out why gh-pages wasn't working, so I made a commit to reload it. Please ignore it.

**Comment by an-OK-squirrel** [comment]
I'll make a normal PR if you want.

**Pull request closed without merging**
